
[_audit]hgghgfh
homePath=$SPLUNK_DB/audit/db
coldPath=$SPLUNK_DB/audit/colddb

[_configtracker]

homePath=$SPLUNK_DB/_configtracker/db
coldPath=$SPLUNK_DB/_configtracker/colddb

[_dsappevent]
homePath=$SPLUNK_DB/_dsappevent/db
coldPath=$SPLUNK_DB/_dsappevent/colddb

[_dsclient]
homePath=$SPLUNK_DB/_dsclient/db
coldPath=$SPLUNK_DB/_dsclient/colddb

[_dsphonehome]
homePath=$SPLUNK_DB/_dsphonehome/db
coldPath=$SPLUNK_DB/_dsphonehome/colddb

[_internal]
homePath=$SPLUNK_DB/_internaldb/db
coldPath=$SPLUNK_DB/_internaldb/colddb

[_introspection]
homePath=$SPLUNK_DB/_introspection/db
coldPath=$SPLUNK_DB/_introspection/colddb

[_telemetry]
homePath=$SPLUNK_DB/_telemetry/db
coldPath=$SPLUNK_DB/_telemetry/colddb

[_thefishbucket]
homePath=$SPLUNK_DB/fishbucket/db
coldPath=$SPLUNK_DB/fishbucket/colddb

[api-service]
homePath=/api-service/db
coldPath=/api-service/colddb

[auth_events]
homePath=/auth_events/db
coldPath=/auth_events/colddb

[auth_events_api-service]
homePath=/auth_events_api-service/db
coldPath=/auth_events_api-service/colddb

[auth_events_data]
homePath=/auth_events_data/db
coldPath=/auth_events_data/colddb

[auth_events_web-application]
homePath=/auth_events_web-application/db
coldPath=/auth_events_web-application/colddb

[demoapp_logs]
homePath=$SPLUNK_DB/demoapp_logs/db
coldPath=$SPLUNK_DB/demoapp_logs/colddb

[eshwar_logs_data]
homePath=/eshwar_logs_data/db
coldPath=/eshwar_logs_data/colddb

[g]
homePath=/g/db
coldPath=/g/colddb

[gg_logs]
homePath=$SPLUNK_DB/gg_logs/db
coldPath=$SPLUNK_DB/gg_logs/colddb

[history]
homePath=$SPLUNK_DB/historydb/db
coldPath=$SPLUNK_DB/historydb/colddb

[hrms]
homePath=$SPLUNK_DB/hrms/db
coldPath=$SPLUNK_DB/hrms/colddb

[jjjjjjjjjj]
homePath=$SPLUNK_DB/jjjjjjjjjj/db
coldPath=$SPLUNK_DB/jjjjjjjjjj/colddb

[loans]
homePath=$SPLUNK_DB/loans/db
coldPath=$SPLUNK_DB/loans/colddb

[main]
homePath=$SPLUNK_DB/defaultdb/db
coldPath=$SPLUNK_DB/defaultdb/colddb

[mani]
homePath=$SPLUNK_DB/mani/db
coldPath=$SPLUNK_DB/mani/colddb

[one]
homePath=$SPLUNK_DB/one/db
coldPath=$SPLUNK_DB/one/colddb

[sample]
homePath=$SPLUNK_DB/sample/db
coldPath=$SPLUNK_DB/sample/colddb

[splunklogger]
homePath=$SPLUNK_DB/splunklogger/db
coldPath=$SPLUNK_DB/splunklogger/colddb

[summary]
homePath=$SPLUNK_DB/summarydb/db
coldPath=$SPLUNK_DB/summarydb/colddb

[u]
homePath=$SPLUNK_DB/u/db
coldPath=$SPLUNK_DB/u/colddb

[uuuuuuuuuuuuuuuuuuuu]
homePath=$SPLUNK_DB/uuuuuuuuuuuuuuuuuuuu/db
coldPath=$SPLUNK_DB/uuuuuuuuuuuuuuuuuuuu/colddb

[wwww]
homePath=$SPLUNK_DB/wwww/db
coldPath=$SPLUNK_DB/wwww/colddb

[y]
homePath=$SPLUNK_DB/y/db
coldPath=$SPLUNK_DB/y/colddb

[yash]
homePath=$SPLUNK_DB/yash/db
coldPath=$SPLUNK_DB/yash/colddb

[yyyy]
homePath=$SPLUNK_DB/yyyy/db
coldPath=$SPLUNK_DB/yyyy/colddb

# App: lans | Business: loans
[aaaa]
homePath=volume:_splunk_home\aaaa\db
coldPath=volume:_splunk_home\aaaa\colddb
thawedPath=volume:_splunk_home\aaaa\thaweddb
